### ISSUE TITLE
뱃지 조회 및 등록 기능 구현

### ISSUE THREAD

**Issue by sooyoungh** [livarter/backend#12]
## Issue: Feature
- 뱃지 기능 구현

## Description
- 회원 가입 시, 뱃지 9개 모두 false로 등록됨
- 이후에 뱃지 부여받으면 true로 업데이트

## Todo
- [x] 회원 가입시 뱃지 자동 등록
- [x] 회원별 뱃지 조회
- [x] 뱃지 부여(등록)
